Fix Electron support (#170)
* Switched PropTypes import from React to 'prop-types' package

* Forgot to --save 'prop-types' npm package + Imported TypeDefinition from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prop-types

* Messed up bool.isRequired, my bad!

* Added icon option support (web-only) in Alert + added a js alert() fallback is Notifications are not supported

* Avoid "error TS2322: Type '{}' is not assignable to type 'null'."

* Avoid "error TS2322: Type '{}' is not assignable to type 'null'." on TodoList sample

* Removed vestigial line preventing Electron execution