Fix incompatibility with tyescript 2.7 compiler
The following no longer compiles:
RX.Styles.createAnimatedViewStyle({
        transform: [{
            translateY: this._topValue
        }, {
            translateX: this._leftValue
        }, {
            scale: this._scaleValue
        }, {
            rotateZ: this._rotationValue.interpolate({
                inputRange: [0, 360],
                outputRange: ['0deg', '360deg']
            })
        }]
    });

Error: Type '[{ translateY: Value; }, { translateX: Value; }, { scale: Value; }, { rotateZ: Value; }]' is not assignable to type '[{ perspective?: AnimatedValue | undefined; rotate?: AnimatedValue | undefined; rotateX?: Animate...'.
        Types of property 'length' are incompatible.
          Type '4' is not assignable to type '1'.