Convert the web Alert from notification to Modal (#219)
* Switched PropTypes import from React to 'prop-types' package

* Forgot to --save 'prop-types' npm package + Imported TypeDefinition from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prop-types

* Messed up bool.isRequired, my bad!

* Added icon option support (web-only) in Alert + added a js alert() fallback is Notifications are not supported

* Avoid "error TS2322: Type '{}' is not assignable to type 'null'."

* Avoid "error TS2322: Type '{}' is not assignable to type 'null'." on TodoList sample

* Removed vestigial line preventing Electron execution

* Converted web specific Alert from a web notification to a customizable Modal

* Added 2 examples of new Alert usage in Hello World sample

* Added support for hover styles. Added documentation. Updated field names and code style for consistency with rest of ReactXP code. Updated default styling for modal alert.